[programs.localnet]
track_node = "SWEETpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/paul/.config/solana/id.json"

[scripts]
test = "mocha -t 1000000 tests/"
